### ISSUE TITLE
matrix-scan Web DEMO2 requires Drosophila

### ISSUE THREAD

**Issue by jvanheld** [rsa-tools/rsat-code#27]
Matrix-scan DEMO2 requires Drosophila, although this genome is only installed on Metazoa and Teaching. 

We should also see how to handle this on the servers that don't support Drosophila (Prokaryotes, Plants, Protists, Fungi). 

Options: 

1. Present this DEMO only on servers where Drosophila melanogaster is supported
2. Find an example that does not depend on Drosophila melanogaster
3. Adapt the options to get rid of the need for Drosophlan genome (by choosing a background model based on the input sequence

**Comment by jvanheld** [comment]
Actually it is sufficient to change the background model from *Organism-specific* to  * Estimate residue probabilities from input sequences*

**Comment by morganeTC** [comment]
This DEMO is linked with the Nature Protocols Paper, that's why it is on Drosophila. As users still use this protocol, removing it seems a bit delicate.

Maybe we would need to update the Protocols, but this is really more on the long term. 

As for now, i would prefer that we keep Drosophila on the servers. i actually do not see any issue with having all the Teaching genomes on all servers (and clearly stating it to warn the users).

**Comment by jvanheld** [comment]
OK for me. We should then include all these genomes in the installation script `$RSAT installer/06_install_organisms.bash`

**Comment by jvanheld** [comment]
Are there other organisms that would be required on all the servers ?

**Comment by morganeTC** [comment]
@jvanheld 

I agree that these genomes should be in the installation script (at least on the public servers, maybe not for anyone installing locally RSAT, because human genomes are quite big)

I don't know the exact list. I think this question will be solved when we know all the organisms required for all DEMOs. If the Teaching server works fine, then the list of organisms is the same as the one needed on Teaching server (except the organisms for phylogenetic footprinting)

**Comment by jvanheld** [comment]
OK, since we agreed on the solution I close this issue, and I open an [issue on rsat-dev](https://github.com/rsa-tools/rsat-dev/issues/12) to add Drosophila to the default organisms installed on all servers.
