### ISSUE TITLE
Message for Genomes in prokaryotes displayed everywhere

### ISSUE THREAD

**Issue by jvanheld** [rsa-tools/rsat-code#29]
There is a prokaryote-specific message displayed on all the forms with a choice of organism, and on all the servers, irrespective of their taxonomic specificity. 

This is sometimes displayed for tools that are never used with prokaryotes (example:`retrieve-variation-sequence`). 

We should evaluate if this message is still relevant. If not it should be suppressed. If yes, it should only appear on the Prokaryote server. 

@amedina-liigh , what do you think ?

**Comment by jvanheld** [comment]
![image](https://user-images.githubusercontent.com/10991210/155230622-a70da8c5-eefd-4c25-81d3-ece0d430f0b8.png)

**Comment by amedina-liigh** [comment]
Now is not a relevant comment, as it was some years ago. 
Was this issue fixed? because I cannot replicate the issue in Metazoa nor Plants, I do not see the legend

![image](https://user-images.githubusercontent.com/27740232/155235442-49f55013-8816-4704-8ae1-8baf393a89c5.png)
![image](https://user-images.githubusercontent.com/27740232/155235472-2076f044-6a97-4a07-a6e8-987f91564f19.png)

**Comment by jvanheld** [comment]
The issue is not specific to `variation-scan`or to the Teaching server, the message also appears in all the forms that require an organism, for instance [gene-info on RSAT Fungi](http://rsat-tagc.univ-mrs.fr/rsat/gene-info_form.cgi)

![image](https://user-images.githubusercontent.com/10991210/155271386-b6dc0e97-73a3-4e1a-8d47-b9da49944fbf.png)

**Comment by jvanheld** [comment]
UI still have it after `git pull`

**Comment by amedina-liigh** [comment]
Not sure what happened but my repo did not commit the chance properly yesterday, now it should be fixed

**Comment by jvanheld** [comment]
Thanks @amedina-liigh , it worked indeed (pulled on fungi). I close the issue.
